[/]
center-active=false
left-active=false
location=2
right-commands-json="{\"commands\":[{\"isActive\":true,\"command\":\"battery=$(headsetcontrol -b 2>/dev/null | grep '%' | sed 's/Level://g;s/^[ \\\\t]*//') && [ -n \\\"$battery\\\" ] && echo \\\"🎧 $battery\\\"\",\"interval\":30,\"uuid\":\"e9383c61-41d7-4670-9f31-570436c63b02\"}]}"
right-index=9