call plug#begin('~/.config/nvim/autoload/plugged')
  Plug 'fedepujol/move.nvim'
  Plug 'lukas-reineke/indent-blankline.nvim'
  Plug 'nvim-lualine/lualine.nvim'
  Plug 'preservim/nerdtree'
  Plug 'rafalbromirski/vim-aurora'
  Plug 'ryanoasis/vim-devicons'
  Plug 'windwp/nvim-autopairs'
  Plug 'Xuyuanp/nerdtree-git-plugin'
  Plug 'zefei/vim-wintabs'
  Plug 'zefei/vim-wintabs-powerline'
call plug#end()
