---
- name: Aplicar configuraciones de GNOME
  hosts: localhost
  
  tasks:
    - name: Configurar tema oscuro
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

    - name: Desactivar confirmación al apagar
      ansible.builtin.command:
        cmd: gsettings set org.gnome.SessionManager logout-prompt false

    - name: Quitar el suspender pantalla
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.session idle-delay 0

    - name: Desactivar workspaces dinámicos
      ansible.builtin.command:
        cmd: gsettings set org.gnome.mutter dynamic-workspaces false

    - name: Configurar número de workspaces
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.wm.preferences num-workspaces 1

    - name: Activar localización del puntero
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface locate-pointer true

    - name: Ajustar reloj
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface clock-format '12h'

    - name: Mostrar segundos en el reloj
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface clock-show-seconds true

    - name: Mostrar día de la semana en el reloj
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface clock-show-weekday true

    - name: Configurar diseño de botones de la ventana
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

    - name: Configurar tema GTK
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'

    - name: Importar configuración de dash-to-panel
      ansible.builtin.command:
        cmd: dconf load /org/gnome/shell/extensions/dash-to-panel/ < ~/.config/dashtopanel.conf
      ignore_errors: true  # Ignorar si el archivo no existe

    - name: Importar configuración de Tilix
      ansible.builtin.command:
        cmd: dconf load /com/gexperts/Tilix/ < ~/.config/tilix.conf
      ignore_errors: true  # Ignorar si el archivo no existe

    - name: Importar configuración de executor
      ansible.builtin.command:
        cmd: dconf load /org/gnome/shell/extensions/executor/ < ~/.config/executor.conf
      ignore_errors: true  # Ignorar si el archivo no existe

    - name: Importar configuración de poweroffmenu
      ansible.builtin.command:
        cmd: dconf load /org/gnome/shell/extensions/bring-out-submenu-of-power-off-logout/ < ~/.config/poweroffmenu.conf
      ignore_errors: true  # Ignorar si el archivo no existe
