---
- name: Remover apps innecesarias
  hosts: localhost
  become: true  # Ejecutar como sudo

  tasks:
    - name: Remover paquetes específicos con sus dependencias
      community.general.pacman:
        name:
          - vlc
          - python-pip
          - python-poetry
        state: absent
        extra_args: --recursive # Elimina dependencias asociadas

    - name: Obtener lista de paquetes huérfanos
      command: pacman -Qdtq
      register: orphaned_packages
      ignore_errors: true  # Ignorar errores si no hay huérfanos

    - name: Comprobar si hay paquetes huérfanos
      set_fact:
        has_orphaned_packages: "{{ orphaned_packages.stdout_lines | length > 0 }}"

    - name: Remover paquetes huérfanos
      community.general.pacman:
        name: "{{ orphaned_packages.stdout_lines }}"
        state: absent
        extra_args: --recursive  # Elimina cualquier dependencia restante
      when: has_orphaned_packages  # Ejecutar solo si hay huérfanos
